# Generated by Django 6.0.1 on 2026-01-13 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Progress date')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='User notes about progress')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='progress_images/%Y/%m/%d/')),
                ('image_type', models.CharField(choices=[('front', 'Front'), ('side', 'Side'), ('back', 'Back'), ('other', 'Other')], default='other', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.progressentry')),
            ],
        ),
        migrations.AddIndex(
            model_name='progressentry',
            index=models.Index(fields=['user', 'date'], name='dashboard_p_user_id_22e794_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progressentry',
            unique_together={('user', 'date')},
        ),
    ]
