# Generated by Django 6.0.1 on 2026-01-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressentry',
            options={'ordering': ['-recorded_on']},
        ),
        migrations.RemoveIndex(
            model_name='progressentry',
            name='dashboard_p_user_id_22e794_idx',
        ),
        migrations.RenameField(
            model_name='progressentry',
            old_name='notes',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='progressimage',
            old_name='progress_entry',
            new_name='entry',
        ),
        migrations.AlterUniqueTogether(
            name='progressentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='recorded_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='progressentry',
            name='body_fat_percentage',
        ),
        migrations.RemoveField(
            model_name='progressentry',
            name='date',
        ),
    ]
