# Generated by Django 6.0.1 on 2026-01-14 03:39

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_progressentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressentry',
            name='recorded_on',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the progress entry'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='progressentry',
            unique_together={('user', 'recorded_on')},
        ),
        migrations.AddIndex(
            model_name='progressentry',
            index=models.Index(fields=['user', 'recorded_on'], name='dashboard_p_user_id_826344_idx'),
        ),
    ]
