# Generated by Django 4.2.27 on 2026-01-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_userprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy'), ('athlete', 'Athlete')], default='moderate', max_length=20),
        ),
    ]
