# Generated by Django 6.0.1 on 2026-04-22 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gym_type', models.CharField(choices=[('crossfit', 'CrossFit'), ('bodybuilding', 'Bodybuilding'), ('boxing', 'Boxing'), ('mma', 'MMA / Martial Arts'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('general', 'General Fitness'), ('zumba', 'Zumba / Dance Fitness'), ('calisthenics', 'Calisthenics'), ('powerlifting', 'Powerlifting'), ('swimming', 'Swimming'), ('cycling', 'Cycling / Spinning'), ('functional', 'Functional Training'), ('kickboxing', 'Kickboxing')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('amenities', models.JSONField(default=list)),
                ('opening_hours', models.JSONField(default=dict)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gym_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gym_covers/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_gyms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('campaign_type', models.CharField(choices=[('welcome', 'Welcome'), ('discount', 'Discount Offer'), ('announcement', 'Announcement'), ('event', 'Event Promotion'), ('newsletter', 'Newsletter')], max_length=20)),
                ('target_radius_km', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='gyms.gym')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gym_media/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='gyms.gym')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GymMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('following', 'Following'), ('member', 'Member')], default='following', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gyms.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='GymMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_from_owner', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_conversations', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gyms.gym')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['city', 'gym_type'], name='gyms_gym_city_4eb5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['latitude', 'longitude'], name='gyms_gym_latitud_2c80a7_idx'),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['owner'], name='gyms_gym_owner_i_eb7aff_idx'),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['is_active', 'city'], name='gyms_gym_is_acti_3e11c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gymmembership',
            unique_together={('user', 'gym')},
        ),
        migrations.AddIndex(
            model_name='gymmessage',
            index=models.Index(fields=['gym', 'conversation_user', 'created_at'], name='gyms_gymmes_gym_id_d988e8_idx'),
        ),
    ]
